name: Feature Preview Build
on:
  push:
    branches:
      - feature/**

jobs:
  deploy:
    if: startsWith(github.head_ref, 'feature/')
    name: Deploy Preview
    environment: preview
    type: deploy
    params:
      preview: true
